global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "source_ip"]
  group_wait: 10s
  group_interval: 999h
  repeat_interval: 999h
  receiver: "ai-agent-webhook"

receivers:
  - name: "ai-agent-webhook"
    webhook_configs:
      - url: "http://ai-agent:5050/alert"
        send_resolved: true
        max_alerts: 1
